# Bollinger Band Mean Reversion with Different Exit Strategies
# Compare 4 different BB exit approaches on USDJPY

spot: "USDJPY"
offsets: [0, 1, 2, 3]
start_date: "01022025"
end_date: "09302025"

# Signal strategy: BB mean reversion (enter on band touch)
signal_strategy: "bb_mean_reversion"
signal_params:
  bb_window: 20
  bb_std: 2.5  # Use 1.0 std to get many more signals throughout the day
  use_rsi_filter: false

# Compare 4 BB exit strategies
labels:
  # Strategy 1: Exit at middle band (MA line) - Quickest exits, highest win rate
  bb_middle:
    pt: null               # No backup PT - rely on BB exit only
    sl: null               # No backup SL - rely on BB exit only
    max_hold: null         # No backup max hold - rely on BB exit only
    use_bb_exit: true
    bb_exit_strategy: "middle"
    # BB params read from signal_params automatically
  
  # Strategy 2: Exit at opposite band - Maximum profit potential
  bb_opposite:
    pt: null
    sl: null
    max_hold: null
    use_bb_exit: true
    bb_exit_strategy: "opposite_band"
  
  # Strategy 3: Exit at partial reversion (50% to middle)
  bb_partial_50:
    pt: null
    sl: null
    max_hold: null
    use_bb_exit: true
    bb_exit_strategy: "partial"
    exit_std_multiplier: 0.5  # Exit at MA ± 0.5*std (halfway to middle)
  
  # Strategy 4: Exit on opposite signal (signal reversal)
  bb_signal:
    pt: null
    sl: null
    max_hold: null
    use_bb_exit: true
    bb_exit_strategy: "signal"
